### ISSUE TITLE
Potential issue with core solver

### ISSUE THREAD

**Issue by jzuhone** [sot/xija#72]
Hi @taldcroft and @matthewdahmer,

I spent the last couple of days digging into the rk2 solver in [core.c](https://github.com/sot/xija/blob/master/xija/core.c). I have a question about these lines:

https://github.com/sot/xija/blob/c9b5b3963924e22530b67a130f3ce897d483eb32/xija/core.c#L83-L87

This (unless I am incorrect) is designed to carry out a midpoint method / RK2 evolution of the ODE, as the equations are consistent with the method as laid out here: 

http://mathworld.wolfram.com/Runge-KuttaMethod.html

However, I think that we are not quite right, since above we update the `y[I]` in place: 

https://github.com/sot/xija/blob/c9b5b3963924e22530b67a130f3ce897d483eb32/xija/core.c#L27

whereas in the linked formula above at MathWorld you are supposed to update the original `y[i]`. Or am I missing something?

**Comment by taldcroft** [comment]
@jzuhone - I have not really thought about this code in 8 years so I don't have any special insight at this point.  If I were writing this today I would definitely document it better, the loop over `rki` is interesting and complicates things a bit.

So all I can say is that empirically it does integrate.  But if you think there is a subtle logic error (entirely possible) and it can integrate *better* then please proceed!  My hunch is that in most cases model errors are related to systematic inadequacy of the fundamental model rather than the integration process, but that's really just a hunch.

**Comment by jzuhone** [comment]
@taldcroft - I think that what happens here is that if I am right (which I am becoming more convinced of) what I think happens is the fact that since we fit our coefficients the slight mismatch in the evolution gets corrected for by the values of the parameters. I'm currently playing around to see what happens if we use the original `y[i]`.

**Comment by jzuhone** [comment]
This issue was more or less addressed by PR #75.

**Comment by taldcroft** [comment]
Agreed, closing!
